#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr  8 15:10:59 2022

@author: youngmin
"""

# Ensemble 앙상블
# 구현방식
# 1.취합
import pandas as pd
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()

X=pd.DataFrame(data.data, columns=data.feature_names)
y=pd.Series(data.target)

y.head()
y.tail()
y.value_counts()

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y,
                                                 test_size=0.3,
                                                 stratify=y,
                                                 random_state=1)

from sklearn.ensemble import VotingClassifier

from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

m1 = KNeighborsClassifier(n_jobs=-1)
m2 = LogisticRegression(n_jobs=-1, random_state=1)
m3 = DecisionTreeClassifier(random_state=1)

estimators=[('knn',m1), ('Lr',m2), ('dt',m3)]


model = VotingClassifier(estimators = estimators,
                         voting='hard',
                         n_jobs=-1)

model.fit(X_train, y_train)

score = model.score(X_train, y_train)


print(f'score (Train) : {score}')

score = model.score(X_test, y_test)
print(f'score (Test) : {score}')

pred = model.predict(X_test[50:51])
print(f'Preditct : {pred}')

print(model.estimators_[0])
print(model.estimators_[1])
print(model.estimators_[2])

pred = model.estimators_[0].predict(X_test[50:51])
print(f'Predict (knn) : {pred}')

pred = model.estimators_[0].predict(X_test[50:51])
print(f'Predict (Lr) : {pred}')

pred = model.estimators_[0].predict(X_test[50:51])
print(f'Predict (dt) : {pred}')










# 2.부스팅
